language: node_js

node_js:
  - "8.11.3"

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

script:
  - yarn build
  - yarn lint
  - yarn test --runInBand --coverage
  - cat ./coverage/lcov.info | yarn coveralls
